language: node_js

addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0' ]
    packages: [ 'libstdc++-4.9-dev', 'clang-4.0' ]

install:
  - mkdir -p ./third_party/mason
  - curl -sSfL https://github.com/mapbox/mason/archive/v0.19.0.tar.gz | tar --gunzip --extract --strip-components=1 --directory=./third_party/mason
  - curl -Ls https://mapbox-release-engineering.s3.amazonaws.com/mbx-ci/latest/mbx-ci-linux-amd64 > mbx-ci && chmod 755 ./mbx-ci
  - npm install --build-from-source
  

before_script:
  - ./mbx-ci aws setup
  - $(./mbx-ci aws credentials --export)

script:
  - npm test
  - ./scripts/publish.sh

matrix:
  include:
    - os: linux
      node_js: 6
      sudo: false
      env: CC='clang-4.0' CXX='clang++-4.0'
    - os: linux
      node_js: 8
      sudo: false
      env: CC='clang-4.0' CXX='clang++-4.0'
    - os: linux
      node_js: 10
      sudo: false
      env: CC='clang-4.0' CXX='clang++-4.0'
    - os: linux
      node_js: 12
      sudo: false
      env: CC='clang-4.0' CXX='clang++-4.0'
    - os: linux
      node_js: 14
      sudo: false
      env: CC='clang-4.0' CXX='clang++-4.0'

    - os: osx
      osx_image: xcode8.2
      node_js: 6
    - os: osx
      osx_image: xcode8.2
      node_js: 8
    - os: osx
      osx_image: xcode8.2
      node_js: 10
    - os: osx
      osx_image: xcode8.2
      node_js: 12
    - os: osx
      osx_image: xcode8.2
      node_js: 14
